name: Output Information
on:
  workflow_dispatch:  # Allows manual trigger of this workflow
jobs:
  info:
    env: 
      demo:${{ secrets.DEMOSEC }}
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub Context
        run: echo "${{ env.demo }}"
